name: dash-seqviz
channels:
  - conda-forge
dependencies:
  - conda-forge::dash>=3
  - conda-forge::nodejs
  - conda-forge::pytest
  - conda-forge::psutil
  - conda-forge::biopython
  - conda-forge::yaml
  - conda-forge::pyyaml
  - conda-forge::rdkit==2024.09.4
  - conda-forge::poppler